swagger: "2.0"
info:
  description: "This is a sample server Petstore server."
  version: "1.0.0"
  title: "Swagger Petstore"
host: "petstore.swagger.io"
basePath: "/v1"
schemes:
- "http"
paths:
  /pets:
    get:
      summary: "List all pets"
      operationId: "listPets"
      tags:
      - "pets"
      responses:
        200:
          description: "An paged array of pets"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Pet"
  /pets/{petId}:
    get:
      summary: "Info for a specific pet"
      operationId: "showPetById"
      tags:
      - "pets"
      parameters:
      - name: "petId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Expected response to a valid request"
          schema:
            $ref: "#/definitions/Pet"
definitions:
  Pet:
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      tag:
        type: "string"
